version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    image: nginx:${IMAGE_TAG}
    labels:
      - inception
    depends_on:
      - wordpress
    env_file:
      - ../.env
    ports:
      - '443:443'
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    image: mariadb:${IMAGE_TAG}
    labels:
      - inception
    env_file:
      - ../.env
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
    secrets:
      - db_creds
      - db_root
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    image: wordpress:${IMAGE_TAG}
    labels:
      - inception
    depends_on:
      - mariadb
      - redis
    env_file:
      - ../.env
    volumes:
      - wp-volume:/var/www/
    secrets:
      - db_creds
      - wp_creds
    networks:
      - inception
    restart: always

  redis:
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    container_name: redis
    image: redis:${IMAGE_TAG}
    labels:
      - inception
    env_file:
      - ../.env
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  adminer:
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    container_name: adminer
    image: adminer:${IMAGE_TAG}
    labels:
      - inception
    depends_on:
      - mariadb
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    networks:
     - inception
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/mariadb

networks:
    inception:
        driver: bridge

secrets:
  db_creds:
    file: ${secrets_dir}/db_creds.txt
  db_root:
    file: ${secrets_dir}/db_root_pass.txt
  wp_creds:
    file: ${secrets_dir}/wp_creds.txt
